### ISSUE TITLE
Option to not surrender 

### ISSUE THREAD

**Issue by danlangford** [pappde/bmai#32]
Many people on [Button Men Online](buttonweavers.com) would love BMAI to not surrender but instead to play the next best move. 

I haven’t looked into the code yet. Is it possible that by parsing the current output I could determine the next best move? Do you think that in theory it would be relatively simple to do?

**Comment by pappde** [comment]
Of course, this means that BMAI thinks it has no chance of winning. That said, since we are using simulations, it could certainly miss a possible unlikely scenario that actually does result in a win.

Check out bmai_ai.cpp around line 1090:

```
	// SURRENDER: if best move is 0% win, then surrender
	if (t.best_score==0)
		t.best_move->m_action = BME_ACTION_SURRENDER;
```

You could certainly disable this behavior (or make it configurable).  What would happen without any other changes is it would then effectively always choose the first move, because right now if two moves have the same "score", it picks the first one.

```
			if (t.score[i] > t.best_score)
				t.SetBestMove(attack, t.score[i]);
```

You could add some randomization to select from multiple moves that have the same score (which may be 0).

**Comment by danlangford** [comment]
Thanks for the insight. I think I’ll try my hand at adding an option to 
BMC_Parser::Parse()
To turn surrender off. That could configure a new option in g_ai. 
mill take it for a spin and let you know if I have questions
