### ISSUE TITLE
support morphing twin die

### ISSUE THREAD

**Issue by danlangford** [pappde/bmai#41]
A button Gluttony has a morphing twin die

![image](https://github.com/pappde/bmai/assets/721364/d6420663-fd41-4a13-b41a-ae1a39cbd25f)

however the codebase doesn't allow for it

>bmai.cpp:708
>```cpp
>	// MORPHING shouldn't be paired with TWIN
>	BM_ERROR( (m_properties & (BME_PROPERTY_MORPHING|BME_PROPERTY_TWIN)) != (BME_PROPERTY_MORPHING|BME_PROPERTY_TWIN) );
>```
>

**Comment by pappde** [comment]
Don't recall the issue - probably it just wasn't clear what the behavior should be. However, most likely an m(1,5) capturing a 6 would become m(6,6). But what happens if an m(1,5) captures a (2,4)?

Depending on that special case, it seems like this shouldn't be hard to support.  In BMC_Die::OnApplyAttackPlayer() there is this code:

```
	if (HasProperty(BME_PROPERTY_MORPHING))
	{
...
		m_sides_max = m_sides[0] = target->GetDie(_move.m_target)->GetSidesMax();
...
	}
```

In which case it would look like:
```
   m_sides_max = 0;
   for (int i=0; i<Dice(); i++)  
      m_sides_max += m_sides[i] = target->GetDie(...)
```

Also, at least one BM_ASSERT and BM_ERROR to remove.

SECONDARY ISSUE
I see a couple of other Morphing combination restrictions (Turbo, Speed) that may need to be allowed.

**Comment by jl8e** [comment]
IIRC, a morphing twin die doesn't behave any differently from a non-twin morphing die: the morphing die twins and un-twins as needed.

**Comment by danlangford** [comment]
@jl8e so m(1,5) capturing a 6 would become m(6). m(1,5) captures a (2,4) and becomes m(2,5)

Is that right ?

**Comment by jl8e** [comment]
yes

**Comment by danlangford** [comment]
other areas this is discussed. specifically interested in the Turbo aspect
https://www.buttonweavers.com/ui/forum.html#!threadId=991
https://github.com/buttonmen-dev/buttonmen/issues/2676

**Comment by danlangford** [comment]
we have tests that prove Morphing Twin is working with #69
