### ISSUE TITLE
Implement Insult skill

### ISSUE THREAD

**Issue by danlangford** [pappde/bmai#53]
Insult (I)	
Cannot be attacked by skill attacks.

**Comment by pappde** [comment]
Seems like this should be straightforward.

```
GenerateValidAttacks()
...
  case BME_ATTACK_TYPE_N_1:
...
  // check all target dice
  for (move.m_target=0; move.m_target<target->GetAvailableDice(); move.m_target++)
...
    if (tgt_die is insult)
      continue;
```

Note there are two parallel for loops that both would need the check.

**Comment by danlangford** [comment]
to add Insult to the enum it would be
```
	BME_PROPERTY_INSULT			=0x100000000, 
```
which is larger than an `int` which I think has some major implications. many methods are expecting an `INT` / `int`

**Comment by pappde** [comment]
A quick workaround would be to replace BME_PROPERTY_RAGE, which is not implemented. 

Otherwise, the easiest solution is probably to just change to 64-bit/U64/long. Depending on the assumptions, this may "just work", so can be quick to prototype. Check out BMC_DieData for where it stores and checks properties.
