### ISSUE TITLE
Implement Value skill

### ISSUE THREAD

**Issue by danlangford** [pappde/bmai#54]
Value: v	
These dice are not scored like normal dice. Instead, a Value Die is scored as if the number of sides it has is equal to the value that it is currently showing. If a Value Die is ever part of an attack, all dice that are captured become Value Dice (i.e. They are scored by the current value they are showing when they are captured, not by their size).

_Interaction with Null: Dice with both Null and Value skills are Null_

_Interaction with Poison: Dice with both Poison and Value skills are Poison dice that score based on the negative of their current value rather than on their number of sides_

**Comment by pappde** [comment]
BMC_Die::GetScore() allows easy implementation of the first part. If BME_PROPERTY_VALUE we can return m_value_total instead of m_sides_max.

For the second part, this is related to Null dice. Look at BMC_Game::ApplyAttackNaturePost() and the null_attacker flag. Then either we want to do something like tgt_die->SetState(BME_STATE_VALUE) or tgt_die->Set(BME_PROPERTY_VALUE). The latter seems more appropriate, but need to look closer to make sure it would work.

**Comment by danlangford** [comment]
thanks for pointing me here

so following this Null example through I find

```cpp
if (null_attacker)
{
	tgt_die->SetState(BME_STATE_NULLIFIED);
}
else
{
	tgt_die->SetState(BME_STATE_CAPTURED);
	attacker->OnDieCaptured(tgt_die);
}
```

and I went around and around and around thinking to myself "where is the state used?" I never saw where the state was used to change the score to 0. and then it dawned on me that `OnDieCaptured()` is where the score is increased so by NOT calling that the score is not changed.  probably a semantic difference between **NOT scoring** and **scoring 0 points**. 

so now I think I have what I need to move forward. this was mainly a status update for my own recollection should I get sidetracked for a long time
