### ISSUE TITLE
bmai tried to shadow attack an invalid target (with shadow twin)

### ISSUE THREAD

**Issue by danlangford** [pappde/bmai#67]
in a game with a couple of twin dice BMAI tried to shadow attack a target thats not valid. here is the rendered board state

![image](https://github.com/user-attachments/assets/eeadfb28-d26a-426b-a384-3c91bdb5a1b7)

here is the BMAI input

```
game 3
fight
player 0 3 29
Y-1:1
Y-1:1
^gst(Z,Z)-8:6
player 1 3 19
(6,6):10
(6,6):10
(6,6):9
ply 2
max_sims 100
min_sims 5
maxbranch 400
surrender off
getaction
quit
```

and some output

> Time: 0.000000 s Sim: 67989  Sims/Sec: 0.000000  Mvs/Sms | 6.0/66.0 | 5.1/39.5 = 80248
> l1 p0 best move (66.0 points, 100.0% win) attack shadow - (10002029)16:6 -> (2000)12:10 
> stats 2/5-100/400/0.50 Time: 0.000000 s Sim: 67989  Sims/Sec: 0.000000  Mvs/Sms | 6.0/66.0 | 5.1/39.5 = 80248
> action
> shadow
> 2
> 0

the `^gst(Z,Z)-8:6` die can only shadow attack 6,7,8 however its trying to shadow attack a 10
ont his particular board state the only possible attack is a Trip attack

relevant skill descriptions are here:

https://www.buttonweavers.com/ui/skills.html#Twin
https://www.buttonweavers.com/ui/skills.html#Shadow
https://www.buttonweavers.com/ui/skills.html#Trip
https://www.buttonweavers.com/ui/skills.html#Stinger
https://www.buttonweavers.com/ui/skills.html#TimeAndSpace

**Comment by pappde** [comment]
I think the problem is a discrepancy between the parsing code and the input syntax, which perhaps was changed?

I believe BMAI is reading "^gst(Z,Z)-8:6" and thinks that Z=8, so m_sides_max  = 16 and m_value_total = 6. So it thinks a shadow attack is valid from 6-16.

Going back to the expected behavior, I can see that "^gst(Z,Z)-8:6" means that Z = 4, and m_sides_max = 8, and m_value_total = 6, so shadow should only be valid from 6-8.  

If you look at  BMC_Parser::ParseDieSides(INT & _pos, INT _die), which is called for both dice "(Z,Z)":

```
		BME_SWING	swing_type = (BME_SWING)(BME_SWING_FIRST + (line[_pos] - BMD_FIRST_SWING_CHAR));
		d->m_swing_type[_die] =  swing_type;
		d->m_sides[_die] = 0;
		p->m_swing_set = BMC_Player::SWING_SET_NOT;
		_pos++;

		// check if swing sides have been defined - NOTE this does not move _pos
		INT sides = ParseDieDefinedSides(_pos);
		if (sides>0)
		{
			d->m_sides[_die] = sides;
			d->m_sides_max += sides;
			p->m_swing_value[swing_type] = sides;
			p->m_swing_set = BMC_Player::SWING_SET_LOCKED;
		}
```

If you look at ParseDieDefinedSides(), you see it scans ahead and returns the number after the "-" (the 8).  So you can see it thinks that the twins are (8,8), so m_sides_max = 16.

However, when the parser reads the value, it reads it as the value of the two dice (arguably inconsistent).

```
   d->m_value_total = atoi(line + pos);
```

**INPUT SYNTAX**
The root cause here I believe may be a change in the input syntax.  Glancing at the perl glue code, I believe the parser is expecting this scenario to be input as

>^gst(Z,Z)-4:6

So it would then interpret this as twin 4-sided dice (max sides 8), with a value total of 6.

**FIX**
There are two ways to fix this.

* A) change the input syntax to "-4:6" for (4,4) twins and leave the parser code as is.
* B) change the parser to read the "-8" and divide by 2 dice to realize there are (4,4) twins

Option (A) is better since it is clear that "Z=4".

Option (B) is better since the "8" and the "6" are both consistently totals.

**Comment by danlangford** [comment]
very insightful, as always. 
_(side note I hope you dont feel obligated to dive into new issues. while I am appreciative of the time, im really hoping you dont feel you need to do this over something else. my intention is that ill come back here and dive deeper later. regardless, thank you)_

I like FIX A, fixing the input generation to have the int after the `-` to be the size of the swing not the total size of the Twin dice.

**Comment by danlangford** [comment]
> adjusted input syntax to have the value represent the size of each die in the Twin. 

many games became unstuck as a result :-)
